name: Setup FFmpeg
description: Setup FFmpeg with cache.

runs:
  using: composite
  steps:
    - name: Get current date
      id: current-date
      shell: bash
      run: |
        echo "daily=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "monthly=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

    - name: Restore ffmpeg cache
      id: cache-ffmpeg
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/bin/ffmpeg
          /usr/local/bin/ffprobe
        key: ffmpeg-cache-${{ runner.os }}-${{ runner.arch }}-${{ steps.current-date.outputs.daily }}
        restore-keys: ffmpeg-cache-${{ runner.os }}-${{ runner.arch }}-${{ steps.current-date.outputs.monthly }}

    - name: Install FFmpeg
      if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        BASE_DELAY=30
        for i in {1..3}; do
          BACKOFF_DELAY=$((BASE_DELAY * (2 ** (i - 1))))
          echo "Attempt $i: Installing FFmpeg..."
          curl -s -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz && \
          tar -xf ffmpeg.tar.xz && \
          mv ffmpeg-*-static/ffmpeg /usr/local/bin/ && \
          mv ffmpeg-*-static/ffprobe /usr/local/bin/ && \
          rm -rf ffmpeg.tar.xz ffmpeg-*-static/ && \
          break || sleep $BACKOFF_DELAY
          if [ $i -eq 3 ]; then
            echo "Failed to install FFmpeg after 3 attempts"
            exit 1
          fi
        done

    - name: FFmpeg version
      shell: bash
      run: |
        ffmpeg -version
