name: autofix.ci # name must be "autofix.ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Setup mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.8.21

      - name: Run tasks
        continue-on-error: true
        run: |
          mise run --continue-on-error check

      - name: autofix.ci
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with:
          fail-fast: false
          commit-message: 'fix: apply automated fixes'
