name: Check Pull Request

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-pr-title:
    name: Semantic PR title
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  status-check:
    name: Status Check
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      pull-requests: read
      checks: read
      statuses: read
    steps:
      - name: Watch PR checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
        run: |
          prev_message=""

          echo "::group::PR checks log"

          while true; do
            all_checks="$( \
              gh pr checks "$pr_number" \
                --json bucket,name \
                --jq 'map(select(.name != "Status Check"))' \
            )"

            failed_checks_length="$( \
              jq -c 'map(select(.bucket == "fail" or .bucket == "cancel")) | length' \
                <<< $all_checks \
            )"

            passed_checks_length="$( \
              jq -c 'map(select(.bucket == "pass" or .bucket == "skipping")) | length' \
                <<< $all_checks \
            )"

            pending_checks_length="$( \
              jq -c 'map(select(.bucket == "pending")) | length' \
                <<< $all_checks \
            )"

            current_message="${failed_checks_length} failing, ${passed_checks_length} successful, and ${pending_checks_length} pending checks"

            if [[ "$current_message" != "$prev_message" ]]; then
              echo "$current_message"
              prev_message="$current_message"
            fi

            if [[ "$failed_checks_length" != "0" ]]; then
              echo "::endgroup::"
              echo "Some checks have failed"
              exit 1
            fi

            if [[ "$pending_checks_length" == "0" ]]; then
              echo "::endgroup::"
              echo "All checks have been completed"
              exit 0
            fi

            sleep 10
          done
