name: CI 1

on:
  pull_request_target:
    branches:
      - main

permissions: {}

jobs:
  ci-1:
    name: CI 1
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - run: sleep 10
      - run: exit 0
