name: CI 2

on:
  push:

permissions: {}

jobs:
  random-failure:
    name: Random failure
    runs-on: ubuntu-22.04
    steps:
      - name: Random failure
        run: |
          exit $((RANDOM % 2))
