name: Sandbox CI#2

on:
  pull_request_target:

jobs:
  sandbox-job:
    name: sandbox-job in ci#2
    runs-on: ubuntu-22.04
    steps:
      - run: |
          {
            echo '```json'
            echo "$github_json"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
        env:
          github_json: ${{ toJSON(github) }}

      - uses: actions/checkout@v4.2.0
        with:
          persist-credentials: false
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 0

      - run: |
          {
            echo '```txt'
            git branch -a
            echo '```'
          } >> $GITHUB_STEP_SUMMARY

      - run: |
          {
            echo '```txt'
            git log -n1
            echo '```'
          } >> $GITHUB_STEP_SUMMARY

      - run: |
          {
            echo '```txt'
            cat sandbox.txt || true
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
