name: Sandbox CI#2

on:
  pull_request_target:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-22.04
    outputs:
      commit: ${{ steps.checkout.outputs.commit }}
      ref: ${{ steps.checkout.outputs.ref }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - run: |
          {
            echo '```json'
            echo "$checkout_json"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
        env:
          checkout_json: ${{ toJSON(steps.checkout.outputs) }}

  sandbox-job:
    name: sandbox-job in ci#2
    runs-on: ubuntu-22.04
    # needs:
    #   - checkout
    steps:
      - run: |
          {
            echo '```json'
            echo "$github_json"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
        env:
          github_json: ${{ toJSON(github) }}

      # - uses: actions/checkout@v4.2.0
      #   with:
      #     persist-credentials: false
      #     ref: refs/pull/${{ github.event.pull_request.number }}/merge
      #     fetch-depth: 0

      # - run: |
      #     {
      #       echo '```txt'
      #       git branch -a
      #       echo '```'
      #     } >> $GITHUB_STEP_SUMMARY

      # - run: |
      #     {
      #       echo '```txt'
      #       git log -n1
      #       echo '```'
      #     } >> $GITHUB_STEP_SUMMARY

      # - run: |
      #     {
      #       echo '```txt'
      #       cat sandbox.txt || true
      #       echo '```'
      #     } >> $GITHUB_STEP_SUMMARY
