name: CI

on:
  push:

permissions: {}

jobs:
  job:
    name: Job
    runs-on: ${{ matrix.value.os }}
    strategy:
      matrix:
        value:
          - os: ubuntu-22.04
            platform: linux/amd64
          - os: ubuntu-22.04-arm
            platform: linux/arm64
    steps:
      - name: Step
        run: |
          echo "${{ fromJSON(matrix) }}"
