name: CI

on:
  push:

permissions: {}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      items: '["__shared__"]'
    steps:
      - run: echo 0

  matrix-job:
    name: Matrix job
    runs-on: ubuntu-22.04
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        item: ${{ fromJSON(needs.prepare.outputs.items) }}
        exclude:
          - item: __shared__
    steps:
      - run: echo '${{ toJSON(matrix) }}'
