name: CI

on:
  push:

  workflow_dispatch:

permissions: {}

jobs:
  checks:
    name: Checks API
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      checks: read
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const checkRuns = await github.paginate(
              github.rest.checks.listForRef,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.pull_request?.head?.sha ?? context.sha,
                per_page: 100,
              },
              (response) => response.data.check_runs,
            );
            console.log(JSON.stringify(checkRuns, null, '\t'));

  statuses:
    name: Statuses API
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      statuses: read
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const commitStatuses = await github.paginate(
              github.rest.repos.listCommitStatusesForRef,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.pull_request?.head?.sha ?? context.sha,
                per_page: 100,
              },
              (response) => response.data,
            );
            console.log(JSON.stringify(commitStatuses, null, '\t'));
