name: CI

on:
  push:

  pull_request:

  pull_request_target:

  workflow_dispatch:

permissions: {}

jobs:
  checks:
    name: Checks API
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      checks: read
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const checksParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request?.head?.sha ?? context.sha,
              per_page: 100,
            };
            console.log(JSON.stringify(checksParams, null, '\t'));
            const { data: { check_runs: checkRuns } } = await github.rest.checks.listForRef(checksParams);
            console.log(JSON.stringify(checkRuns, null, '\t'));

  statuses:
    name: Statuses API
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      statuses: read
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const statusesParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request?.head?.sha ?? context.sha,
              per_page: 100,
            };
            console.log(JSON.stringify(statusesParams, null, '\t'));
            const { data: commitStatuses } = await github.rest.repos.listCommitStatusesForRef(statusesParams);
            console.log(JSON.stringify(commitStatuses, null, '\t'));
