name: Pull Request Labeler

on:
  pull_request_target:
    branches:
      - main

permissions: {}

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: true
