name: Lint

on:
  push:
    branches:
      - main

  pull_request_target:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  pre-checkout:
    name: Pre checkout
    uses: ./.github/workflows/pre-checkout.yaml
    permissions:
      contents: read

  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    needs:
      - pre-checkout
    env:
      cache-path: ${{ github.workspace }}/.cache/.eslintcache
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ needs.pre-checkout.outputs.sha }}
          fetch-depth: 1

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Cache eslint
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        env:
          prefix: eslint-cache
          platform: ${{ runner.os }}-${{ runner.arch }}
          hash: ${{ hashFiles('**/pnpm-lock.yaml', '**/eslint.config.ts') }}
          primary: ${{ needs.pre-checkout.outputs.sha }}
        with:
          path: ${{ env.cache-path }}
          key: >-
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}-${{ env.primary }}
          restore-keys: |
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}-${{ env.primary }}
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}

      - name: Run eslint
        run: |
          pnpm exec eslint \
            --cache \
            --cache-location '${{ env.cache-path }}' \
            --cache-strategy content

  typecheck:
    name: TypeCheck
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    needs:
      - pre-checkout
    env:
      cache-path: ${{ github.workspace }}/.cache/.tsbuildinfo
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ needs.pre-checkout.outputs.sha }}
          fetch-depth: 1

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Cache typecheck
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        env:
          prefix: typecheck-cache
          platform: ${{ runner.os }}-${{ runner.arch }}
          hash: ${{ hashFiles('**/pnpm-lock.yaml', '**/tsconfig.json') }}
          primary: ${{ needs.pre-checkout.outputs.sha }}
        with:
          path: ${{ env.cache-path }}
          key: >-
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}-${{ env.primary }}
          restore-keys: |
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}-${{ env.primary }}
            ${{ env.prefix }}-${{ env.platform }}-${{ env.hash }}

      - name: Run typecheck
        run: |
          pnpm exec tsc \
            --noEmit \
            --incremental \
            --tsBuildInfoFile '${{ env.cache-path }}'
