name: Lint (actions)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.ya?ml
      - '**/action.ya?ml'
      - .github/actionlint-matcher.json

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/*.ya?ml
      - '**/action.ya?ml'
      - .github/actionlint-matcher.json

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Add actionlint problem matcher
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color

  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read # Required for zizmor
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
          persona: auditor
