name: Release Manager

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  release_suffix_name: taiyme

jobs:
  parse-version:
    name: Parse version
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    if: "${{ ! startsWith(github.event.head_commit.message, 'chore(release): bump to v') }}"
    outputs:
      upstream-version: ${{ steps.get-upstream.outputs.base-version }}
      current-version: ${{ steps.get-current.outputs.full-version }}
      parsed-version: ${{ steps.result.outputs.parsed-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Get upstream version
        id: get-upstream
        run: |
          v="$(jq -r '.upstreamVersion // empty' package.json)"

          if [[ -z "$v" ]]; then
            echo "::error::Missing required field 'upstreamVersion'"
            exit 1
          fi

          echo "base-version=${v%%-*}" >> "$GITHUB_OUTPUT"

      - name: Get current version
        id: get-current
        run: |
          v="$(jq -r '.version // empty' package.json)"

          if [[ -z "$v" ]]; then
            echo "::error::Missing required field 'version'"
            exit 1
          fi

          if [[ "$v" == *-"$release_suffix_name".* ]]; then
            base_version="${v%-${release_suffix_name}.*}"
            count="${v##*-${release_suffix_name}.}"
          else
            base_version="$v"
            count=""
          fi

          echo "full-version=${v}" >> "$GITHUB_OUTPUT"
          echo "base-version=${base_version}" >> "$GITHUB_OUTPUT"
          echo "count=${count}" >> "$GITHUB_OUTPUT"

      - name: Parse version
        id: result
        env:
          upstream_version: ${{ steps.get-upstream.outputs.base-version }}
          current_version: ${{ steps.get-current.outputs.base-version }}
          current_count: ${{ steps.get-current.outputs.count }}
        run: |
          if [[ "$current_version" == "$upstream_version" ]]; then
            if [[ -z "$current_count" ]]; then
              parsed_version="${current_version}-${release_suffix_name}.0"
            else
              parsed_version="${current_version}-${release_suffix_name}.$((current_count + 1))"
            fi
          else
            parsed_version="${upstream_version}-${release_suffix_name}.0"
          fi

          if [[ "$parsed_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+-${release_suffix_name}\.[0-9]+$ ]]; then
            echo "parsed-version=${parsed_version}" >> "$GITHUB_OUTPUT"
          else
            echo "::error::Incorrect version format: '${parsed_version}'"
            exit 1
          fi

  bump-version:
    name: Bump version
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs:
      - parse-version
    permissions:
      contents: read
    env:
      parsed_version: ${{ needs.parse-version.outputs.parsed-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Update package.json (root)
        run: |
          jq --arg v "$parsed_version" -- '.version = $v' package.json > tmp
          mv tmp package.json
          cat package.json

      # - name: Update package.json (misskey-js)
      #   working-directory: packages/misskey-js
      #   run: |
      #     jq --arg v "$parsed_version" -- '.version = $v' package.json > tmp
      #     mv tmp package.json
      #     cat package.json

      # - name: Update compose_example.yml
      #   run: |
      #     old_docker_image="$(yq '.services.web.image' compose_example.yml)"
      #     new_docker_image='${{ vars.DOCKER_IMAGE_NAME }}:${{ needs.parse-version.outputs.new_version }}'
      #     sed -i "s|image: ${old_docker_image}|image: ${new_docker_image}|g" compose_example.yml

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      #   with:
      #     name: bump_version_files
      #     path: |
      #       package.json
      #       packages/misskey-js/package.json
      #       compose_example.yml

  log:
    name: Log
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs:
      - parse-version
    permissions: {}
    steps:
      - name: Log
        env:
          upstream_version: ${{ needs.parse-version.outputs.upstream-version }}
          current_version: ${{ needs.parse-version.outputs.current-version }}
          parsed_version: ${{ needs.parse-version.outputs.parsed-version }}
        run: |
          echo "upstream_version: ${upstream_version}"
          echo "current_version: ${current_version}"
          echo "parsed_version: ${parsed_version}"
