name: Sandbox

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          delimiter="$(openssl rand -hex 8)"
          {
            echo "multi_message<<${delimiter}"
            echo "message 1"
            echo "message 2"
            echo "message 3"
            echo $delimiter
          } >> $GITHUB_ENV

      - run: |
          echo "${multi_message}"

      - run: |
          echo "${{ env.multi_message }}"
