name: Sandbox

on:
  workflow_dispatch:
    inputs:
      message:
        type: string

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "rng="$(openssl rand -hex 8)"" >> $GITHUB_ENV

      - run: |
          echo "$rng"

      - run: |
          echo "${{ env.rng }}"

      - run: |
          echo "$message"
        env:
          message: ${{ inputs.message }}

      - run: |
          echo "${{ env.message }}"
        env:
          message: ${{ inputs.message }}
