name: Sandbox

on:
  workflow_dispatch:
    inputs:
      message_1:
        type: string
      message_2:
        type: string
      message_3:
        type: string

jobs:
  try_job:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        message_1:
          - foo
          - bar
        message_2:
          - hoge
          - fuga
    steps:
      - run: |
          echo 'try_job'

      - run: |
          echo 'echo msg:'
          echo "$msg"
        env:
          msg: ${{ matrix.message_1 }}-${{ matrix.message_2 }}

      - run: |
          echo 'echo matrix_json'
          echo "$matrix_json"
        env:
          matrix_json: ${{ toJson(matrix) }}

      - run: |
          echo 'echo matrix_str'
          echo "$matrix_str"
        env:
          matrix_str: ${{ fromJson(matrix) }}

      - if: matrix.message_1 == 'foo' && matrix.message_2 == 'fuga'
        run: exit 1

  finally_job:
    runs-on: ubuntu-22.04
    if: always()
    needs:
      - try_job
    steps:
      - run: |
          echo 'finally_job'
