name: Sandbox

on:
  workflow_dispatch:
    inputs:
      message_1:
        type: string
      message_2:
        type: string
      message_3:
        type: string

jobs:
  try_job:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        message_1:
          - foo
          - bar
        message_2:
          - hoge
          - fuga
    steps:
      - run: |
          echo 'try_job'

      - run: |
          echo 'echo msg:'
          echo "$msg"
        env:
          msg: ${{ matrix.message_1 }}-${{ matrix.message_2 }}

      - run: |
          echo 'echo matrix_json'
          echo "$matrix_json"
        env:
          matrix_json: ${{ toJSON(matrix) }}

      - if: matrix.message_1 == 'foo' && matrix.message_2 == 'fuga'
        run: exit 1

  try_job2:
    runs-on: ubuntu-22.04
    if: success()
    needs:
      - try_job
    steps:
      - run: |
          echo 'try_job2'

  try_job3:
    runs-on: ubuntu-22.04
    if: failure()
    needs:
      - try_job
    steps:
      - run: |
          echo 'try_job2'

  finally_job:
    runs-on: ubuntu-22.04
    if: always()
    needs:
      - try_job
      - try_job2
      - try_job3
    steps:
      - run: |
          echo 'finally_job'

      - run: |
          echo 'echo needs_json'
          echo "$needs_json"
        env:
          needs_json: ${{ toJSON(needs) }}

      - run: |
          echo 'needs.*.result'
          echo "$needs_result"
        env:
          needs_result: ${{ toJSON(needs.*.result) }}

      - if: contains(needs.*.result, 'failure')
        run: exit 1
